includes:
- configs/models/viva/defaults.yaml

optimizer:
  type: adam_w
  params:
    lr: 0.0001 #5e-5 
    eps: 1e-8 #1e-8

scheduler:
  type: warmup_cosine
  params:
    num_warmup_steps: 1
    num_training_steps: 5

training:
  batch_size: 128
  lr_scheduler: false
  # Don't forget to update schedule_attributes if you update this
  max_updates: 5
  max_epochs: 5
  find_unused_parameters: true
  early_stop:
    enabled: false
    patience: 2
    criteria: viva/logit_bce
    minimize: true

