model_config:
  viva_model:
    losses:
    - type: logit_bce
    video_encoder:
      type: timesformer
      params:
        num_output_features: 1
        pool_type: avg
        out_dim: 2048
        three_d: true
    audio_encoder: 
      type: resnet18_audio
      params: 
        embedding_dim: 512
        num_output_features: 1
        pool_type: avg
        out_dim: 2048
        three_d: false
    tabular_transforms: 
      in_dim: 2
      out_dim: 512
    text_encoder: 
      type: transformer
    interaction_layer: 
      input_dim: 2560
      hidden_dim: 1024
      output_dim: 2048
    classifier:
      type: mlp
      num_labels: 2
      params:
        in_dim: 2048
        out_dim: 2
    dropout: 0.1

        
        